import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { getAddress } from "viem";
import catalog from "../../data/reviewed-stock-catalog.base-mainnet.json";
import { stockCatalogEvidence, stocks, stockSymbols } from "../../lib/stocks";

const canonicalAddressSet = `${stocks
  .map((stock) => `${stock.symbol}:${stock.mainnetAddress.toLowerCase()}`)
  .join("\n")}\n`;
const addressSetSha256 = createHash("sha256").update(canonicalAddressSet).digest("hex");

if (addressSetSha256 !== stockCatalogEvidence.addressSetSha256) {
  throw new Error("Reviewed catalog address-set hash does not match its records");
}
if (new Set(stocks.map((stock) => stock.symbol)).size !== stocks.length) {
  throw new Error("Reviewed catalog contains a duplicate symbol");
}
if (new Set(stocks.map((stock) => stock.mainnetAddress.toLowerCase())).size !== stocks.length) {
  throw new Error("Reviewed catalog contains a duplicate address");
}
if (stocks.some((stock) => getAddress(stock.mainnetAddress) !== stock.mainnetAddress)) {
  throw new Error("Reviewed catalog contains an address without its exact EIP-55 checksum");
}
if (stocks.some((stock, index) => stock.symbol !== stockSymbols[index])) {
  throw new Error("Reviewed catalog rail order does not match the typed symbol order");
}
if (!Number.isSafeInteger(catalog.reviewedSource.rpcVerifiedAtBlock)) {
  throw new Error("Reviewed catalog is missing its RPC verification block");
}

const generatedSolidity = `// SPDX-License-Identifier: MIT
// Generated by scripts/contracts/check-catalog.ts from the reviewed catalog artifact.
pragma solidity 0.8.36;

library ReviewedStocks {
    function mainnet() internal pure returns (address[] memory stocks) {
        stocks = new address[](${stocks.length});
${stocks.map((stock, index) => `        stocks[${index}] = ${stock.mainnetAddress};`).join("\n")}
    }
}
`;
const generatedPath = resolve(process.cwd(), "contracts/src/generated/ReviewedStocks.sol");
if (readFileSync(generatedPath, "utf8") !== generatedSolidity) {
  throw new Error("Generated Solidity stock catalog is stale");
}

console.log(
  `validated ${stocks.length} reviewed stocks from catalog ${stockCatalogEvidence.addressSetSha256}`,
);
