//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// IB20
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const ib20Abi = [
  {
    type: "function",
    inputs: [],
    name: "BURN_BLOCKED_ROLE",
    outputs: [{ name: "", internalType: "bytes32", type: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "BURN_ROLE",
    outputs: [{ name: "", internalType: "bytes32", type: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "DEFAULT_ADMIN_ROLE",
    outputs: [{ name: "", internalType: "bytes32", type: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "DOMAIN_SEPARATOR",
    outputs: [{ name: "", internalType: "bytes32", type: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "METADATA_ROLE",
    outputs: [{ name: "", internalType: "bytes32", type: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "MINT_RECEIVER_POLICY",
    outputs: [{ name: "", internalType: "bytes32", type: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "MINT_ROLE",
    outputs: [{ name: "", internalType: "bytes32", type: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "PAUSE_ROLE",
    outputs: [{ name: "", internalType: "bytes32", type: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "TRANSFER_EXECUTOR_POLICY",
    outputs: [{ name: "", internalType: "bytes32", type: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "TRANSFER_RECEIVER_POLICY",
    outputs: [{ name: "", internalType: "bytes32", type: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "TRANSFER_SENDER_POLICY",
    outputs: [{ name: "", internalType: "bytes32", type: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "UNPAUSE_ROLE",
    outputs: [{ name: "", internalType: "bytes32", type: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "owner", internalType: "address", type: "address" },
      { name: "spender", internalType: "address", type: "address" },
    ],
    name: "allowance",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "spender", internalType: "address", type: "address" },
      { name: "amount", internalType: "uint256", type: "uint256" },
    ],
    name: "approve",
    outputs: [{ name: "", internalType: "bool", type: "bool" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "account", internalType: "address", type: "address" }],
    name: "balanceOf",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "amount", internalType: "uint256", type: "uint256" }],
    name: "burn",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "from", internalType: "address", type: "address" },
      { name: "amount", internalType: "uint256", type: "uint256" },
    ],
    name: "burnBlocked",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "amount", internalType: "uint256", type: "uint256" },
      { name: "memo", internalType: "bytes32", type: "bytes32" },
    ],
    name: "burnWithMemo",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [],
    name: "contractURI",
    outputs: [{ name: "", internalType: "string", type: "string" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "decimals",
    outputs: [{ name: "", internalType: "uint8", type: "uint8" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "eip712Domain",
    outputs: [
      { name: "fields", internalType: "bytes1", type: "bytes1" },
      { name: "name", internalType: "string", type: "string" },
      { name: "version", internalType: "string", type: "string" },
      { name: "chainId", internalType: "uint256", type: "uint256" },
      { name: "verifyingContract", internalType: "address", type: "address" },
      { name: "salt", internalType: "bytes32", type: "bytes32" },
      { name: "extensions", internalType: "uint256[]", type: "uint256[]" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "role", internalType: "bytes32", type: "bytes32" }],
    name: "getRoleAdmin",
    outputs: [{ name: "", internalType: "bytes32", type: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "role", internalType: "bytes32", type: "bytes32" },
      { name: "account", internalType: "address", type: "address" },
    ],
    name: "grantRole",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "role", internalType: "bytes32", type: "bytes32" },
      { name: "account", internalType: "address", type: "address" },
    ],
    name: "hasRole",
    outputs: [{ name: "", internalType: "bool", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      {
        name: "feature",
        internalType: "enum IB20.PausableFeature",
        type: "uint8",
      },
    ],
    name: "isPaused",
    outputs: [{ name: "", internalType: "bool", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "to", internalType: "address", type: "address" },
      { name: "amount", internalType: "uint256", type: "uint256" },
    ],
    name: "mint",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "to", internalType: "address", type: "address" },
      { name: "amount", internalType: "uint256", type: "uint256" },
      { name: "memo", internalType: "bytes32", type: "bytes32" },
    ],
    name: "mintWithMemo",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [],
    name: "name",
    outputs: [{ name: "", internalType: "string", type: "string" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "owner", internalType: "address", type: "address" }],
    name: "nonces",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      {
        name: "features",
        internalType: "enum IB20.PausableFeature[]",
        type: "uint8[]",
      },
    ],
    name: "pause",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [],
    name: "pausedFeatures",
    outputs: [
      {
        name: "",
        internalType: "enum IB20.PausableFeature[]",
        type: "uint8[]",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "owner", internalType: "address", type: "address" },
      { name: "spender", internalType: "address", type: "address" },
      { name: "value", internalType: "uint256", type: "uint256" },
      { name: "deadline", internalType: "uint256", type: "uint256" },
      { name: "v", internalType: "uint8", type: "uint8" },
      { name: "r", internalType: "bytes32", type: "bytes32" },
      { name: "s", internalType: "bytes32", type: "bytes32" },
    ],
    name: "permit",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "policyScope", internalType: "bytes32", type: "bytes32" }],
    name: "policyId",
    outputs: [{ name: "", internalType: "uint64", type: "uint64" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "renounceLastAdmin",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "role", internalType: "bytes32", type: "bytes32" },
      { name: "callerConfirmation", internalType: "address", type: "address" },
    ],
    name: "renounceRole",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "role", internalType: "bytes32", type: "bytes32" },
      { name: "account", internalType: "address", type: "address" },
    ],
    name: "revokeRole",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "role", internalType: "bytes32", type: "bytes32" },
      { name: "newAdminRole", internalType: "bytes32", type: "bytes32" },
    ],
    name: "setRoleAdmin",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [],
    name: "supplyCap",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "symbol",
    outputs: [{ name: "", internalType: "string", type: "string" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "totalSupply",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "to", internalType: "address", type: "address" },
      { name: "amount", internalType: "uint256", type: "uint256" },
    ],
    name: "transfer",
    outputs: [{ name: "", internalType: "bool", type: "bool" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "from", internalType: "address", type: "address" },
      { name: "to", internalType: "address", type: "address" },
      { name: "amount", internalType: "uint256", type: "uint256" },
    ],
    name: "transferFrom",
    outputs: [{ name: "", internalType: "bool", type: "bool" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "from", internalType: "address", type: "address" },
      { name: "to", internalType: "address", type: "address" },
      { name: "amount", internalType: "uint256", type: "uint256" },
      { name: "memo", internalType: "bytes32", type: "bytes32" },
    ],
    name: "transferFromWithMemo",
    outputs: [{ name: "", internalType: "bool", type: "bool" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "to", internalType: "address", type: "address" },
      { name: "amount", internalType: "uint256", type: "uint256" },
      { name: "memo", internalType: "bytes32", type: "bytes32" },
    ],
    name: "transferWithMemo",
    outputs: [{ name: "", internalType: "bool", type: "bool" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      {
        name: "features",
        internalType: "enum IB20.PausableFeature[]",
        type: "uint8[]",
      },
    ],
    name: "unpause",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "newURI", internalType: "string", type: "string" }],
    name: "updateContractURI",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "newName", internalType: "string", type: "string" }],
    name: "updateName",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "policyScope", internalType: "bytes32", type: "bytes32" },
      { name: "newPolicyId", internalType: "uint64", type: "uint64" },
    ],
    name: "updatePolicy",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "newSupplyCap", internalType: "uint256", type: "uint256" }],
    name: "updateSupplyCap",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "newSymbol", internalType: "string", type: "string" }],
    name: "updateSymbol",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "owner",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "spender",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "amount",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "Approval",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "caller",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      { name: "from", internalType: "address", type: "address", indexed: true },
      {
        name: "amount",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "BurnedBlocked",
  },
  { type: "event", anonymous: false, inputs: [], name: "ContractURIUpdated" },
  { type: "event", anonymous: false, inputs: [], name: "EIP712DomainChanged" },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "previousAdmin",
        internalType: "address",
        type: "address",
        indexed: true,
      },
    ],
    name: "LastAdminRenounced",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "caller",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      { name: "memo", internalType: "bytes32", type: "bytes32", indexed: true },
    ],
    name: "Memo",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "updater",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "newName",
        internalType: "string",
        type: "string",
        indexed: false,
      },
    ],
    name: "NameUpdated",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "updater",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "features",
        internalType: "enum IB20.PausableFeature[]",
        type: "uint8[]",
        indexed: false,
      },
    ],
    name: "Paused",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "policyScope",
        internalType: "bytes32",
        type: "bytes32",
        indexed: true,
      },
      {
        name: "oldPolicyId",
        internalType: "uint64",
        type: "uint64",
        indexed: false,
      },
      {
        name: "newPolicyId",
        internalType: "uint64",
        type: "uint64",
        indexed: false,
      },
    ],
    name: "PolicyUpdated",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      { name: "role", internalType: "bytes32", type: "bytes32", indexed: true },
      {
        name: "previousAdminRole",
        internalType: "bytes32",
        type: "bytes32",
        indexed: true,
      },
      {
        name: "newAdminRole",
        internalType: "bytes32",
        type: "bytes32",
        indexed: true,
      },
    ],
    name: "RoleAdminChanged",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      { name: "role", internalType: "bytes32", type: "bytes32", indexed: true },
      {
        name: "account",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "sender",
        internalType: "address",
        type: "address",
        indexed: true,
      },
    ],
    name: "RoleGranted",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      { name: "role", internalType: "bytes32", type: "bytes32", indexed: true },
      {
        name: "account",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "sender",
        internalType: "address",
        type: "address",
        indexed: true,
      },
    ],
    name: "RoleRevoked",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "updater",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "oldSupplyCap",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
      {
        name: "newSupplyCap",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "SupplyCapUpdated",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "updater",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "newSymbol",
        internalType: "string",
        type: "string",
        indexed: false,
      },
    ],
    name: "SymbolUpdated",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      { name: "from", internalType: "address", type: "address", indexed: true },
      { name: "to", internalType: "address", type: "address", indexed: true },
      {
        name: "amount",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "Transfer",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "updater",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "features",
        internalType: "enum IB20.PausableFeature[]",
        type: "uint8[]",
        indexed: false,
      },
    ],
    name: "Unpaused",
  },
  { type: "error", inputs: [], name: "AccessControlBadConfirmation" },
  {
    type: "error",
    inputs: [
      { name: "account", internalType: "address", type: "address" },
      { name: "neededRole", internalType: "bytes32", type: "bytes32" },
    ],
    name: "AccessControlUnauthorizedAccount",
  },
  {
    type: "error",
    inputs: [{ name: "account", internalType: "address", type: "address" }],
    name: "AccountNotBlocked",
  },
  {
    type: "error",
    inputs: [
      {
        name: "feature",
        internalType: "enum IB20.PausableFeature",
        type: "uint8",
      },
    ],
    name: "ContractPaused",
  },
  { type: "error", inputs: [], name: "EmptyFeatureSet" },
  {
    type: "error",
    inputs: [{ name: "deadline", internalType: "uint256", type: "uint256" }],
    name: "ExpiredSignature",
  },
  {
    type: "error",
    inputs: [
      { name: "spender", internalType: "address", type: "address" },
      { name: "allowance", internalType: "uint256", type: "uint256" },
      { name: "needed", internalType: "uint256", type: "uint256" },
    ],
    name: "InsufficientAllowance",
  },
  {
    type: "error",
    inputs: [
      { name: "sender", internalType: "address", type: "address" },
      { name: "balance", internalType: "uint256", type: "uint256" },
      { name: "needed", internalType: "uint256", type: "uint256" },
    ],
    name: "InsufficientBalance",
  },
  { type: "error", inputs: [], name: "InvalidAmount" },
  {
    type: "error",
    inputs: [{ name: "approver", internalType: "address", type: "address" }],
    name: "InvalidApprover",
  },
  {
    type: "error",
    inputs: [{ name: "receiver", internalType: "address", type: "address" }],
    name: "InvalidReceiver",
  },
  {
    type: "error",
    inputs: [{ name: "sender", internalType: "address", type: "address" }],
    name: "InvalidSender",
  },
  {
    type: "error",
    inputs: [
      { name: "signer", internalType: "address", type: "address" },
      { name: "owner", internalType: "address", type: "address" },
    ],
    name: "InvalidSigner",
  },
  {
    type: "error",
    inputs: [{ name: "spender", internalType: "address", type: "address" }],
    name: "InvalidSpender",
  },
  {
    type: "error",
    inputs: [
      { name: "currentSupply", internalType: "uint256", type: "uint256" },
      { name: "proposedCap", internalType: "uint256", type: "uint256" },
    ],
    name: "InvalidSupplyCap",
  },
  { type: "error", inputs: [], name: "LastAdminCannotRenounce" },
  { type: "error", inputs: [], name: "NonPayable" },
  { type: "error", inputs: [], name: "NotSoleAdmin" },
  {
    type: "error",
    inputs: [
      { name: "policyScope", internalType: "bytes32", type: "bytes32" },
      { name: "policyId", internalType: "uint64", type: "uint64" },
    ],
    name: "PolicyForbids",
  },
  {
    type: "error",
    inputs: [{ name: "policyId", internalType: "uint64", type: "uint64" }],
    name: "PolicyNotFound",
  },
  {
    type: "error",
    inputs: [
      { name: "cap", internalType: "uint256", type: "uint256" },
      { name: "attempted", internalType: "uint256", type: "uint256" },
    ],
    name: "SupplyCapExceeded",
  },
  { type: "error", inputs: [], name: "Unauthorized" },
  {
    type: "error",
    inputs: [{ name: "policyScope", internalType: "bytes32", type: "bytes32" }],
    name: "UnsupportedPolicyType",
  },
] as const;

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// IB20Asset
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const ib20AssetAbi = [
  {
    type: "function",
    inputs: [],
    name: "BURN_BLOCKED_ROLE",
    outputs: [{ name: "", internalType: "bytes32", type: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "BURN_ROLE",
    outputs: [{ name: "", internalType: "bytes32", type: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "DEFAULT_ADMIN_ROLE",
    outputs: [{ name: "", internalType: "bytes32", type: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "DOMAIN_SEPARATOR",
    outputs: [{ name: "", internalType: "bytes32", type: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "METADATA_ROLE",
    outputs: [{ name: "", internalType: "bytes32", type: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "MINT_RECEIVER_POLICY",
    outputs: [{ name: "", internalType: "bytes32", type: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "MINT_ROLE",
    outputs: [{ name: "", internalType: "bytes32", type: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "OPERATOR_ROLE",
    outputs: [{ name: "", internalType: "bytes32", type: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "PAUSE_ROLE",
    outputs: [{ name: "", internalType: "bytes32", type: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "TRANSFER_EXECUTOR_POLICY",
    outputs: [{ name: "", internalType: "bytes32", type: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "TRANSFER_RECEIVER_POLICY",
    outputs: [{ name: "", internalType: "bytes32", type: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "TRANSFER_SENDER_POLICY",
    outputs: [{ name: "", internalType: "bytes32", type: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "UNPAUSE_ROLE",
    outputs: [{ name: "", internalType: "bytes32", type: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "WAD_PRECISION",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "owner", internalType: "address", type: "address" },
      { name: "spender", internalType: "address", type: "address" },
    ],
    name: "allowance",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "internalCalls", internalType: "bytes[]", type: "bytes[]" },
      { name: "id", internalType: "string", type: "string" },
      { name: "description", internalType: "string", type: "string" },
      { name: "uri", internalType: "string", type: "string" },
    ],
    name: "announce",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "spender", internalType: "address", type: "address" },
      { name: "amount", internalType: "uint256", type: "uint256" },
    ],
    name: "approve",
    outputs: [{ name: "", internalType: "bool", type: "bool" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "account", internalType: "address", type: "address" }],
    name: "balanceOf",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "recipients", internalType: "address[]", type: "address[]" },
      { name: "amounts", internalType: "uint256[]", type: "uint256[]" },
    ],
    name: "batchMint",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "amount", internalType: "uint256", type: "uint256" }],
    name: "burn",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "from", internalType: "address", type: "address" },
      { name: "amount", internalType: "uint256", type: "uint256" },
    ],
    name: "burnBlocked",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "amount", internalType: "uint256", type: "uint256" },
      { name: "memo", internalType: "bytes32", type: "bytes32" },
    ],
    name: "burnWithMemo",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [],
    name: "contractURI",
    outputs: [{ name: "", internalType: "string", type: "string" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "decimals",
    outputs: [{ name: "", internalType: "uint8", type: "uint8" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "eip712Domain",
    outputs: [
      { name: "fields", internalType: "bytes1", type: "bytes1" },
      { name: "name", internalType: "string", type: "string" },
      { name: "version", internalType: "string", type: "string" },
      { name: "chainId", internalType: "uint256", type: "uint256" },
      { name: "verifyingContract", internalType: "address", type: "address" },
      { name: "salt", internalType: "bytes32", type: "bytes32" },
      { name: "extensions", internalType: "uint256[]", type: "uint256[]" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "key", internalType: "string", type: "string" }],
    name: "extraMetadata",
    outputs: [{ name: "", internalType: "string", type: "string" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "role", internalType: "bytes32", type: "bytes32" }],
    name: "getRoleAdmin",
    outputs: [{ name: "", internalType: "bytes32", type: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "role", internalType: "bytes32", type: "bytes32" },
      { name: "account", internalType: "address", type: "address" },
    ],
    name: "grantRole",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "role", internalType: "bytes32", type: "bytes32" },
      { name: "account", internalType: "address", type: "address" },
    ],
    name: "hasRole",
    outputs: [{ name: "", internalType: "bool", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "id", internalType: "string", type: "string" }],
    name: "isAnnouncementIdUsed",
    outputs: [{ name: "", internalType: "bool", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      {
        name: "feature",
        internalType: "enum IB20.PausableFeature",
        type: "uint8",
      },
    ],
    name: "isPaused",
    outputs: [{ name: "", internalType: "bool", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "to", internalType: "address", type: "address" },
      { name: "amount", internalType: "uint256", type: "uint256" },
    ],
    name: "mint",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "to", internalType: "address", type: "address" },
      { name: "amount", internalType: "uint256", type: "uint256" },
      { name: "memo", internalType: "bytes32", type: "bytes32" },
    ],
    name: "mintWithMemo",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [],
    name: "multiplier",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "name",
    outputs: [{ name: "", internalType: "string", type: "string" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "owner", internalType: "address", type: "address" }],
    name: "nonces",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      {
        name: "features",
        internalType: "enum IB20.PausableFeature[]",
        type: "uint8[]",
      },
    ],
    name: "pause",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [],
    name: "pausedFeatures",
    outputs: [
      {
        name: "",
        internalType: "enum IB20.PausableFeature[]",
        type: "uint8[]",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "owner", internalType: "address", type: "address" },
      { name: "spender", internalType: "address", type: "address" },
      { name: "value", internalType: "uint256", type: "uint256" },
      { name: "deadline", internalType: "uint256", type: "uint256" },
      { name: "v", internalType: "uint8", type: "uint8" },
      { name: "r", internalType: "bytes32", type: "bytes32" },
      { name: "s", internalType: "bytes32", type: "bytes32" },
    ],
    name: "permit",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "policyScope", internalType: "bytes32", type: "bytes32" }],
    name: "policyId",
    outputs: [{ name: "", internalType: "uint64", type: "uint64" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "renounceLastAdmin",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "role", internalType: "bytes32", type: "bytes32" },
      { name: "callerConfirmation", internalType: "address", type: "address" },
    ],
    name: "renounceRole",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "role", internalType: "bytes32", type: "bytes32" },
      { name: "account", internalType: "address", type: "address" },
    ],
    name: "revokeRole",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "account", internalType: "address", type: "address" }],
    name: "scaledBalanceOf",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "role", internalType: "bytes32", type: "bytes32" },
      { name: "newAdminRole", internalType: "bytes32", type: "bytes32" },
    ],
    name: "setRoleAdmin",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [],
    name: "supplyCap",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "symbol",
    outputs: [{ name: "", internalType: "string", type: "string" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "scaledBalance", internalType: "uint256", type: "uint256" }],
    name: "toRawBalance",
    outputs: [{ name: "rawBalance", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "rawBalance", internalType: "uint256", type: "uint256" }],
    name: "toScaledBalance",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "totalSupply",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "to", internalType: "address", type: "address" },
      { name: "amount", internalType: "uint256", type: "uint256" },
    ],
    name: "transfer",
    outputs: [{ name: "", internalType: "bool", type: "bool" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "from", internalType: "address", type: "address" },
      { name: "to", internalType: "address", type: "address" },
      { name: "amount", internalType: "uint256", type: "uint256" },
    ],
    name: "transferFrom",
    outputs: [{ name: "", internalType: "bool", type: "bool" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "from", internalType: "address", type: "address" },
      { name: "to", internalType: "address", type: "address" },
      { name: "amount", internalType: "uint256", type: "uint256" },
      { name: "memo", internalType: "bytes32", type: "bytes32" },
    ],
    name: "transferFromWithMemo",
    outputs: [{ name: "", internalType: "bool", type: "bool" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "to", internalType: "address", type: "address" },
      { name: "amount", internalType: "uint256", type: "uint256" },
      { name: "memo", internalType: "bytes32", type: "bytes32" },
    ],
    name: "transferWithMemo",
    outputs: [{ name: "", internalType: "bool", type: "bool" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      {
        name: "features",
        internalType: "enum IB20.PausableFeature[]",
        type: "uint8[]",
      },
    ],
    name: "unpause",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "newURI", internalType: "string", type: "string" }],
    name: "updateContractURI",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "key", internalType: "string", type: "string" },
      { name: "value", internalType: "string", type: "string" },
    ],
    name: "updateExtraMetadata",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "newMultiplier", internalType: "uint256", type: "uint256" }],
    name: "updateMultiplier",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "newName", internalType: "string", type: "string" }],
    name: "updateName",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "policyScope", internalType: "bytes32", type: "bytes32" },
      { name: "newPolicyId", internalType: "uint64", type: "uint64" },
    ],
    name: "updatePolicy",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "newSupplyCap", internalType: "uint256", type: "uint256" }],
    name: "updateSupplyCap",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "newSymbol", internalType: "string", type: "string" }],
    name: "updateSymbol",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "caller",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      { name: "id", internalType: "string", type: "string", indexed: false },
      {
        name: "description",
        internalType: "string",
        type: "string",
        indexed: false,
      },
      { name: "uri", internalType: "string", type: "string", indexed: false },
    ],
    name: "Announcement",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "owner",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "spender",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "amount",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "Approval",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "caller",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      { name: "from", internalType: "address", type: "address", indexed: true },
      {
        name: "amount",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "BurnedBlocked",
  },
  { type: "event", anonymous: false, inputs: [], name: "ContractURIUpdated" },
  { type: "event", anonymous: false, inputs: [], name: "EIP712DomainChanged" },
  {
    type: "event",
    anonymous: false,
    inputs: [{ name: "id", internalType: "string", type: "string", indexed: false }],
    name: "EndAnnouncement",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      { name: "key", internalType: "string", type: "string", indexed: false },
      { name: "value", internalType: "string", type: "string", indexed: false },
    ],
    name: "ExtraMetadataUpdated",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "previousAdmin",
        internalType: "address",
        type: "address",
        indexed: true,
      },
    ],
    name: "LastAdminRenounced",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "caller",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      { name: "memo", internalType: "bytes32", type: "bytes32", indexed: true },
    ],
    name: "Memo",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "multiplier",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "MultiplierUpdated",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "updater",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "newName",
        internalType: "string",
        type: "string",
        indexed: false,
      },
    ],
    name: "NameUpdated",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "updater",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "features",
        internalType: "enum IB20.PausableFeature[]",
        type: "uint8[]",
        indexed: false,
      },
    ],
    name: "Paused",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "policyScope",
        internalType: "bytes32",
        type: "bytes32",
        indexed: true,
      },
      {
        name: "oldPolicyId",
        internalType: "uint64",
        type: "uint64",
        indexed: false,
      },
      {
        name: "newPolicyId",
        internalType: "uint64",
        type: "uint64",
        indexed: false,
      },
    ],
    name: "PolicyUpdated",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      { name: "role", internalType: "bytes32", type: "bytes32", indexed: true },
      {
        name: "previousAdminRole",
        internalType: "bytes32",
        type: "bytes32",
        indexed: true,
      },
      {
        name: "newAdminRole",
        internalType: "bytes32",
        type: "bytes32",
        indexed: true,
      },
    ],
    name: "RoleAdminChanged",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      { name: "role", internalType: "bytes32", type: "bytes32", indexed: true },
      {
        name: "account",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "sender",
        internalType: "address",
        type: "address",
        indexed: true,
      },
    ],
    name: "RoleGranted",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      { name: "role", internalType: "bytes32", type: "bytes32", indexed: true },
      {
        name: "account",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "sender",
        internalType: "address",
        type: "address",
        indexed: true,
      },
    ],
    name: "RoleRevoked",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "updater",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "oldSupplyCap",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
      {
        name: "newSupplyCap",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "SupplyCapUpdated",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "updater",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "newSymbol",
        internalType: "string",
        type: "string",
        indexed: false,
      },
    ],
    name: "SymbolUpdated",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      { name: "from", internalType: "address", type: "address", indexed: true },
      { name: "to", internalType: "address", type: "address", indexed: true },
      {
        name: "amount",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "Transfer",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "updater",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "features",
        internalType: "enum IB20.PausableFeature[]",
        type: "uint8[]",
        indexed: false,
      },
    ],
    name: "Unpaused",
  },
  { type: "error", inputs: [], name: "AccessControlBadConfirmation" },
  {
    type: "error",
    inputs: [
      { name: "account", internalType: "address", type: "address" },
      { name: "neededRole", internalType: "bytes32", type: "bytes32" },
    ],
    name: "AccessControlUnauthorizedAccount",
  },
  {
    type: "error",
    inputs: [{ name: "account", internalType: "address", type: "address" }],
    name: "AccountNotBlocked",
  },
  {
    type: "error",
    inputs: [{ name: "id", internalType: "string", type: "string" }],
    name: "AnnouncementIdAlreadyUsed",
  },
  { type: "error", inputs: [], name: "AnnouncementInProgress" },
  {
    type: "error",
    inputs: [
      {
        name: "feature",
        internalType: "enum IB20.PausableFeature",
        type: "uint8",
      },
    ],
    name: "ContractPaused",
  },
  { type: "error", inputs: [], name: "EmptyBatch" },
  { type: "error", inputs: [], name: "EmptyFeatureSet" },
  {
    type: "error",
    inputs: [{ name: "deadline", internalType: "uint256", type: "uint256" }],
    name: "ExpiredSignature",
  },
  {
    type: "error",
    inputs: [
      { name: "spender", internalType: "address", type: "address" },
      { name: "allowance", internalType: "uint256", type: "uint256" },
      { name: "needed", internalType: "uint256", type: "uint256" },
    ],
    name: "InsufficientAllowance",
  },
  {
    type: "error",
    inputs: [
      { name: "sender", internalType: "address", type: "address" },
      { name: "balance", internalType: "uint256", type: "uint256" },
      { name: "needed", internalType: "uint256", type: "uint256" },
    ],
    name: "InsufficientBalance",
  },
  {
    type: "error",
    inputs: [{ name: "call", internalType: "bytes", type: "bytes" }],
    name: "InternalCallFailed",
  },
  {
    type: "error",
    inputs: [{ name: "call", internalType: "bytes", type: "bytes" }],
    name: "InternalCallMalformed",
  },
  { type: "error", inputs: [], name: "InvalidAmount" },
  {
    type: "error",
    inputs: [{ name: "approver", internalType: "address", type: "address" }],
    name: "InvalidApprover",
  },
  { type: "error", inputs: [], name: "InvalidMetadataKey" },
  { type: "error", inputs: [], name: "InvalidMultiplier" },
  {
    type: "error",
    inputs: [{ name: "receiver", internalType: "address", type: "address" }],
    name: "InvalidReceiver",
  },
  {
    type: "error",
    inputs: [{ name: "sender", internalType: "address", type: "address" }],
    name: "InvalidSender",
  },
  {
    type: "error",
    inputs: [
      { name: "signer", internalType: "address", type: "address" },
      { name: "owner", internalType: "address", type: "address" },
    ],
    name: "InvalidSigner",
  },
  {
    type: "error",
    inputs: [{ name: "spender", internalType: "address", type: "address" }],
    name: "InvalidSpender",
  },
  {
    type: "error",
    inputs: [
      { name: "currentSupply", internalType: "uint256", type: "uint256" },
      { name: "proposedCap", internalType: "uint256", type: "uint256" },
    ],
    name: "InvalidSupplyCap",
  },
  { type: "error", inputs: [], name: "LastAdminCannotRenounce" },
  {
    type: "error",
    inputs: [
      { name: "leftLen", internalType: "uint256", type: "uint256" },
      { name: "rightLen", internalType: "uint256", type: "uint256" },
    ],
    name: "LengthMismatch",
  },
  { type: "error", inputs: [], name: "NonPayable" },
  { type: "error", inputs: [], name: "NotSoleAdmin" },
  {
    type: "error",
    inputs: [
      { name: "policyScope", internalType: "bytes32", type: "bytes32" },
      { name: "policyId", internalType: "uint64", type: "uint64" },
    ],
    name: "PolicyForbids",
  },
  {
    type: "error",
    inputs: [{ name: "policyId", internalType: "uint64", type: "uint64" }],
    name: "PolicyNotFound",
  },
  {
    type: "error",
    inputs: [
      { name: "cap", internalType: "uint256", type: "uint256" },
      { name: "attempted", internalType: "uint256", type: "uint256" },
    ],
    name: "SupplyCapExceeded",
  },
  { type: "error", inputs: [], name: "Unauthorized" },
  {
    type: "error",
    inputs: [{ name: "policyScope", internalType: "bytes32", type: "bytes32" }],
    name: "UnsupportedPolicyType",
  },
] as const;

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// SowmorrowVault
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const sowmorrowVaultAbi = [
  {
    type: "constructor",
    inputs: [
      { name: "initialOwner", internalType: "address", type: "address" },
      { name: "initialStocks", internalType: "address[]", type: "address[]" },
      {
        name: "initialMinGiftAmountsRaw",
        internalType: "uint256[]",
        type: "uint256[]",
      },
      { name: "startPaused", internalType: "bool", type: "bool" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [],
    name: "MAX_BATCH",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "MAX_MIN_GIFT_AMOUNT_RAW",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "VERSION",
    outputs: [{ name: "", internalType: "string", type: "string" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "acceptOwnership",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "giftId", internalType: "uint256", type: "uint256" }],
    name: "claim",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "giftIds", internalType: "uint256[]", type: "uint256[]" }],
    name: "claimMany",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "stock", internalType: "address", type: "address" },
      { name: "recipient", internalType: "address", type: "address" },
      { name: "amountRaw", internalType: "uint256", type: "uint256" },
      { name: "unlockAt", internalType: "uint64", type: "uint64" },
      { name: "noteHash", internalType: "bytes32", type: "bytes32" },
    ],
    name: "createGift",
    outputs: [{ name: "giftId", internalType: "uint256", type: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [],
    name: "creationPaused",
    outputs: [{ name: "", internalType: "bool", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "giftId", internalType: "uint256", type: "uint256" }],
    name: "getGift",
    outputs: [
      {
        name: "gift",
        internalType: "struct SowmorrowVault.Gift",
        type: "tuple",
        components: [
          { name: "sender", internalType: "address", type: "address" },
          { name: "recipient", internalType: "address", type: "address" },
          { name: "stock", internalType: "address", type: "address" },
          { name: "unlockAt", internalType: "uint64", type: "uint64" },
          {
            name: "status",
            internalType: "enum SowmorrowVault.GiftStatus",
            type: "uint8",
          },
          { name: "amountRaw", internalType: "uint256", type: "uint256" },
          { name: "noteHash", internalType: "bytes32", type: "bytes32" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "stock", internalType: "address", type: "address" }],
    name: "minGiftAmountRaw",
    outputs: [{ name: "amountRaw", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "nextGiftId",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "owner",
    outputs: [{ name: "", internalType: "address", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "pendingOwner",
    outputs: [{ name: "", internalType: "address", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "renounceOwnership",
    outputs: [],
    stateMutability: "pure",
  },
  {
    type: "function",
    inputs: [{ name: "paused", internalType: "bool", type: "bool" }],
    name: "setCreationPaused",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "stock", internalType: "address", type: "address" },
      { name: "amountRaw", internalType: "uint256", type: "uint256" },
    ],
    name: "setMinGiftAmountRaw",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "stock", internalType: "address", type: "address" },
      { name: "supported", internalType: "bool", type: "bool" },
      { name: "minAmountRaw", internalType: "uint256", type: "uint256" },
    ],
    name: "setSupportedStock",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "stock", internalType: "address", type: "address" }],
    name: "supportedStock",
    outputs: [{ name: "supported", internalType: "bool", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "stock", internalType: "address", type: "address" }],
    name: "totalEscrowed",
    outputs: [{ name: "amountRaw", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "newOwner", internalType: "address", type: "address" }],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [{ name: "paused", internalType: "bool", type: "bool", indexed: false }],
    name: "CreationPausedSet",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "giftId",
        internalType: "uint256",
        type: "uint256",
        indexed: true,
      },
      {
        name: "recipient",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "stock",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "amountRaw",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "GiftClaimed",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "giftId",
        internalType: "uint256",
        type: "uint256",
        indexed: true,
      },
      {
        name: "sender",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "recipient",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "stock",
        internalType: "address",
        type: "address",
        indexed: false,
      },
      {
        name: "amountRaw",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
      {
        name: "unlockAt",
        internalType: "uint64",
        type: "uint64",
        indexed: false,
      },
      {
        name: "noteHash",
        internalType: "bytes32",
        type: "bytes32",
        indexed: false,
      },
    ],
    name: "GiftCreated",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "stock",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "amountRaw",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "MinGiftAmountSet",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "previousOwner",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "newOwner",
        internalType: "address",
        type: "address",
        indexed: true,
      },
    ],
    name: "OwnershipTransferStarted",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "previousOwner",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "newOwner",
        internalType: "address",
        type: "address",
        indexed: true,
      },
    ],
    name: "OwnershipTransferred",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "stock",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      { name: "supported", internalType: "bool", type: "bool", indexed: false },
    ],
    name: "SupportedStockSet",
  },
  {
    type: "error",
    inputs: [
      { name: "supplied", internalType: "uint256", type: "uint256" },
      { name: "maximum", internalType: "uint256", type: "uint256" },
    ],
    name: "BatchTooLarge",
  },
  {
    type: "error",
    inputs: [{ name: "paused", internalType: "bool", type: "bool" }],
    name: "CreationPauseUnchanged",
  },
  { type: "error", inputs: [], name: "CreationPaused" },
  { type: "error", inputs: [], name: "EmptyBatch" },
  {
    type: "error",
    inputs: [
      { name: "stock", internalType: "address", type: "address" },
      { name: "supplied", internalType: "uint256", type: "uint256" },
      { name: "minimum", internalType: "uint256", type: "uint256" },
    ],
    name: "GiftAmountBelowMinimum",
  },
  {
    type: "error",
    inputs: [{ name: "giftId", internalType: "uint256", type: "uint256" }],
    name: "GiftNotActive",
  },
  {
    type: "error",
    inputs: [{ name: "giftId", internalType: "uint256", type: "uint256" }],
    name: "GiftNotFound",
  },
  {
    type: "error",
    inputs: [
      { name: "giftId", internalType: "uint256", type: "uint256" },
      { name: "unlockAt", internalType: "uint64", type: "uint64" },
      { name: "currentTime", internalType: "uint256", type: "uint256" },
    ],
    name: "GiftStillLocked",
  },
  {
    type: "error",
    inputs: [
      { name: "stocksLength", internalType: "uint256", type: "uint256" },
      { name: "minAmountsLength", internalType: "uint256", type: "uint256" },
    ],
    name: "InitialStocksMinAmountsLengthMismatch",
  },
  {
    type: "error",
    inputs: [{ name: "recipient", internalType: "address", type: "address" }],
    name: "InvalidRecipient",
  },
  {
    type: "error",
    inputs: [
      { name: "stock", internalType: "address", type: "address" },
      { name: "amountRaw", internalType: "uint256", type: "uint256" },
      { name: "maximum", internalType: "uint256", type: "uint256" },
    ],
    name: "MinGiftAmountExceedsMaximum",
  },
  {
    type: "error",
    inputs: [
      { name: "stock", internalType: "address", type: "address" },
      { name: "amountRaw", internalType: "uint256", type: "uint256" },
    ],
    name: "MinGiftAmountMustBeZeroToDisable",
  },
  {
    type: "error",
    inputs: [
      { name: "stock", internalType: "address", type: "address" },
      { name: "amountRaw", internalType: "uint256", type: "uint256" },
    ],
    name: "MinGiftAmountUnchanged",
  },
  {
    type: "error",
    inputs: [{ name: "stock", internalType: "address", type: "address" }],
    name: "MinGiftAmountZero",
  },
  {
    type: "error",
    inputs: [
      { name: "giftId", internalType: "uint256", type: "uint256" },
      { name: "caller", internalType: "address", type: "address" },
      { name: "recipient", internalType: "address", type: "address" },
    ],
    name: "NotGiftRecipient",
  },
  {
    type: "error",
    inputs: [{ name: "owner", internalType: "address", type: "address" }],
    name: "OwnableInvalidOwner",
  },
  {
    type: "error",
    inputs: [{ name: "account", internalType: "address", type: "address" }],
    name: "OwnableUnauthorizedAccount",
  },
  { type: "error", inputs: [], name: "OwnershipRenunciationDisabled" },
  { type: "error", inputs: [], name: "ReentrancyGuardReentrantCall" },
  {
    type: "error",
    inputs: [{ name: "stock", internalType: "address", type: "address" }],
    name: "StockAssetInterfaceInvalid",
  },
  {
    type: "error",
    inputs: [{ name: "stock", internalType: "address", type: "address" }],
    name: "StockMultiplierInvalid",
  },
  {
    type: "error",
    inputs: [{ name: "stock", internalType: "address", type: "address" }],
    name: "StockNotAsset",
  },
  {
    type: "error",
    inputs: [{ name: "stock", internalType: "address", type: "address" }],
    name: "StockNotB20",
  },
  {
    type: "error",
    inputs: [{ name: "stock", internalType: "address", type: "address" }],
    name: "StockNotInitialized",
  },
  {
    type: "error",
    inputs: [
      { name: "stock", internalType: "address", type: "address" },
      { name: "precision", internalType: "uint256", type: "uint256" },
    ],
    name: "StockPrecisionInvalid",
  },
  {
    type: "error",
    inputs: [
      { name: "stock", internalType: "address", type: "address" },
      { name: "supported", internalType: "bool", type: "bool" },
    ],
    name: "StockSupportUnchanged",
  },
  {
    type: "error",
    inputs: [{ name: "stock", internalType: "address", type: "address" }],
    name: "TokenTransferFailed",
  },
  {
    type: "error",
    inputs: [
      { name: "stock", internalType: "address", type: "address" },
      { name: "expected", internalType: "uint256", type: "uint256" },
      { name: "balanceBefore", internalType: "uint256", type: "uint256" },
      { name: "balanceAfter", internalType: "uint256", type: "uint256" },
    ],
    name: "UnexpectedTokenBalanceDelta",
  },
  {
    type: "error",
    inputs: [
      { name: "unlockAt", internalType: "uint64", type: "uint64" },
      { name: "currentTime", internalType: "uint256", type: "uint256" },
    ],
    name: "UnlockNotInFuture",
  },
  {
    type: "error",
    inputs: [{ name: "stock", internalType: "address", type: "address" }],
    name: "UnsupportedStock",
  },
  { type: "error", inputs: [], name: "ZeroAmount" },
] as const;
